config/routes.rb
RubyKsiazki::Application.routes.draw do
  resources :opinions

  resources :publishing_houses

  resources :books

  get "users/new"

  resources :parkings

end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
  attr_accessible :id_book, :id_user, :number, :text
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  # GET /opinions
  # GET /opinions.json
  def index
    @opinions = Opinion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @opinions }
    end
  end

  # GET /opinions/1
  # GET /opinions/1.json
  def show
    @opinion = Opinion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @opinion }
    end
  end

  # GET /opinions/new
  # GET /opinions/new.json
  def new
    @opinion = Opinion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @opinion }
    end
  end

  # GET /opinions/1/edit
  def edit
    @opinion = Opinion.find(params[:id])
  end

  # POST /opinions
  # POST /opinions.json
  def create
    @opinion = Opinion.new(params[:opinion])

    respond_to do |format|
      if @opinion.save
        format.html { redirect_to @opinion, notice: 'Opinion was successfully created.' }
        format.json { render json: @opinion, status: :created, location: @opinion }
      else
        format.html { render action: "new" }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /opinions/1
  # PUT /opinions/1.json
  def update
    @opinion = Opinion.find(params[:id])

    respond_to do |format|
      if @opinion.update_attributes(params[:opinion])
        format.html { redirect_to @opinion, notice: 'Opinion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opinions/1
  # DELETE /opinions/1.json
  def destroy
    @opinion = Opinion.find(params[:id])
    @opinion.destroy

    respond_to do |format|
      format.html { redirect_to opinions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/opinions/_form.html.erb
<%= form_for(@opinion) do |f| %>
  <% if @opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
      <% @opinion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_book %><br />
    <%= f.number_field :id_book %>
  </div>
  <div class="field">
    <%= f.label :id_user %><br />
    <%= f.number_field :id_user %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/opinions/edit.html.erb
<h1>Editing opinion</h1>

<%= render 'form' %>

<%= link_to 'Show', @opinion %> |
<%= link_to 'Back', opinions_path %>

app/views/opinions/index.html.erb
<h1>Listing opinions</h1>

<table>
  <tr>
    <th>Id book</th>
    <th>Id user</th>
    <th>Text</th>
    <th>Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @opinions.each do |opinion| %>
  <tr>
    <td><%= opinion.id_book %></td>
    <td><%= opinion.id_user %></td>
    <td><%= opinion.text %></td>
    <td><%= opinion.number %></td>
    <td><%= link_to 'Show', opinion %></td>
    <td><%= link_to 'Edit', edit_opinion_path(opinion) %></td>
    <td><%= link_to 'Destroy', opinion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Opinion', new_opinion_path %>

app/views/opinions/new.html.erb
<h1>New opinion</h1>

<%= render 'form' %>

<%= link_to 'Back', opinions_path %>

app/views/opinions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id book:</b>
  <%= @opinion.id_book %>
</p>

<p>
  <b>Id user:</b>
  <%= @opinion.id_user %>
</p>

<p>
  <b>Text:</b>
  <%= @opinion.text %>
</p>

<p>
  <b>Number:</b>
  <%= @opinion.number %>
</p>


<%= link_to 'Edit', edit_opinion_path(@opinion) %> |
<%= link_to 'Back', opinions_path %>