config/routes.rb
RubyKsiazki::Application.routes.draw do
  resources :opinions

  resources :publishing_houses

  resources :books

  get "users/new"

  resources :parkings

end

app/models/parking.rb
class Parking < ActiveRecord::Base
  attr_accessible :adres, :pojemnosc
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  # GET /parkings
  # GET /parkings.json
  def index
    @parkings = Parking.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parkings }
    end
  end

  # GET /parkings/1
  # GET /parkings/1.json
  def show
    @parking = Parking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @parking }
    end
  end

  # GET /parkings/new
  # GET /parkings/new.json
  def new
    @parking = Parking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @parking }
    end
  end

  # GET /parkings/1/edit
  def edit
    @parking = Parking.find(params[:id])
  end

  # POST /parkings
  # POST /parkings.json
  def create
    @parking = Parking.new(params[:parking])

    respond_to do |format|
      if @parking.save
        format.html { redirect_to @parking, notice: 'Parking was successfully created.' }
        format.json { render json: @parking, status: :created, location: @parking }
      else
        format.html { render action: "new" }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parkings/1
  # PUT /parkings/1.json
  def update
    @parking = Parking.find(params[:id])

    respond_to do |format|
      if @parking.update_attributes(params[:parking])
        format.html { redirect_to @parking, notice: 'Parking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parkings/1
  # DELETE /parkings/1.json
  def destroy
    @parking = Parking.find(params[:id])
    @parking.destroy

    respond_to do |format|
      format.html { redirect_to parkings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/parkings/_form.html.erb
<%= form_for(@parking) do |f| %>
  <% if @parking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parking.errors.count, "error") %> prohibited this parking from being saved:</h2>

      <ul>
      <% @parking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :adres %><br />
    <%= f.text_field :adres %>
  </div>
  <div class="field">
    <%= f.label :pojemnosc %><br />
    <%= f.number_field :pojemnosc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parkings/edit.html.erb
<h1>Editing parking</h1>

<%= render 'form' %>

<%= link_to 'Show', @parking %> |
<%= link_to 'Back', parkings_path %>

app/views/parkings/index.html.erb
<h1>Listing parkings</h1>

<table>
  <tr>
    <th>Adres</th>
    <th>Pojemnosc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parkings.each do |parking| %>
  <tr>
    <td><%= parking.adres %></td>
    <td><%= parking.pojemnosc %></td>
    <td><%= link_to 'Show', parking %></td>
    <td><%= link_to 'Edit', edit_parking_path(parking) %></td>
    <td><%= link_to 'Destroy', parking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Parking', new_parking_path %>

app/views/parkings/new.html.erb
<h1>New parking</h1>

<%= render 'form' %>

<%= link_to 'Back', parkings_path %>

app/views/parkings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Adres:</b>
  <%= @parking.adres %>
</p>

<p>
  <b>Pojemnosc:</b>
  <%= @parking.pojemnosc %>
</p>


<%= link_to 'Edit', edit_parking_path(@parking) %> |
<%= link_to 'Back', parkings_path %>