config/routes.rb
RubyKsiazki::Application.routes.draw do
  resources :opinions

  resources :publishing_houses

  resources :books

  get "users/new"

  resources :parkings

end

app/controllers/publishing_houses_controller.rb
class PublishingHousesController < ApplicationController
  # GET /publishing_houses
  # GET /publishing_houses.json
  def index
    @publishing_houses = PublishingHouse.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publishing_houses }
    end
  end

  # GET /publishing_houses/1
  # GET /publishing_houses/1.json
  def show
    @publishing_house = PublishingHouse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publishing_house }
    end
  end

  # GET /publishing_houses/new
  # GET /publishing_houses/new.json
  def new
    @publishing_house = PublishingHouse.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publishing_house }
    end
  end

  # GET /publishing_houses/1/edit
  def edit
    @publishing_house = PublishingHouse.find(params[:id])
  end

  # POST /publishing_houses
  # POST /publishing_houses.json
  def create
    @publishing_house = PublishingHouse.new(params[:publishing_house])

    respond_to do |format|
      if @publishing_house.save
        format.html { redirect_to @publishing_house, notice: 'Publishing house was successfully created.' }
        format.json { render json: @publishing_house, status: :created, location: @publishing_house }
      else
        format.html { render action: "new" }
        format.json { render json: @publishing_house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publishing_houses/1
  # PUT /publishing_houses/1.json
  def update
    @publishing_house = PublishingHouse.find(params[:id])

    respond_to do |format|
      if @publishing_house.update_attributes(params[:publishing_house])
        format.html { redirect_to @publishing_house, notice: 'Publishing house was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @publishing_house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishing_houses/1
  # DELETE /publishing_houses/1.json
  def destroy
    @publishing_house = PublishingHouse.find(params[:id])
    @publishing_house.destroy

    respond_to do |format|
      format.html { redirect_to publishing_houses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/publishing_houses_helper.rb
module PublishingHousesHelper
end

app/views/publishing_houses/_form.html.erb
<%= form_for(@publishing_house) do |f| %>
  <% if @publishing_house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publishing_house.errors.count, "error") %> prohibited this publishing_house from being saved:</h2>

      <ul>
      <% @publishing_house.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_book %><br />
    <%= f.number_field :id_book %>
  </div>
  <div class="field">
    <%= f.label :name_publishing %><br />
    <%= f.text_field :name_publishing %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publishing_houses/edit.html.erb
<h1>Editing publishing_house</h1>

<%= render 'form' %>

<%= link_to 'Show', @publishing_house %> |
<%= link_to 'Back', publishing_houses_path %>

app/views/publishing_houses/index.html.erb
<h1>Listing publishing_houses</h1>

<table>
  <tr>
    <th>Id book</th>
    <th>Name publishing</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @publishing_houses.each do |publishing_house| %>
  <tr>
    <td><%= publishing_house.id_book %></td>
    <td><%= publishing_house.name_publishing %></td>
    <td><%= link_to 'Show', publishing_house %></td>
    <td><%= link_to 'Edit', edit_publishing_house_path(publishing_house) %></td>
    <td><%= link_to 'Destroy', publishing_house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Publishing house', new_publishing_house_path %>

app/views/publishing_houses/new.html.erb
<h1>New publishing_house</h1>

<%= render 'form' %>

<%= link_to 'Back', publishing_houses_path %>

app/views/publishing_houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id book:</b>
  <%= @publishing_house.id_book %>
</p>

<p>
  <b>Name publishing:</b>
  <%= @publishing_house.name_publishing %>
</p>


<%= link_to 'Edit', edit_publishing_house_path(@publishing_house) %> |
<%= link_to 'Back', publishing_houses_path %>